### ISSUE TITLE
Wrong Range in TCGA KIRC dataset

### ISSUE THREAD

**Issue by keckelt** [Caleydo/caleydo_data_hdf#12]
* Release number or git hash: latest @ develop (commit 9dfd793443f4cc4b2c989bf6d9db6b0ed4d1d3c5)
* Web browser version and OS: Chrome 59 @ Fedora 25
* Environment (local or deployed): local

### Steps to reproduce
1. Either open in Stratomex with **TCGA KIRC** Data and open "4 TCGA Subtypes" from mRNA-seq dataset or call the problematic request directly:
http://localhost:8080/api/dataset/matrix/tcgaKircMrna-Seq/hist?range=%22%22%7B%22m1%22%22%238dd3c7%22(42%2C46%2C58%2C210%2C228%2C287%2C365%2C449%2C451%2C27%2C47%2C65%2C67%2C76%2C87%2C104%2C108%2C143%2C156%2C194%2C211%2C234%2C253%2C266%2C282%2C322%2C325%2C328%2C329%2C355%2C376%2C395%2C400%2C402%2C459%2C462%2C465%2C471%2C43%2C52%3A54%2C56%2C73%2C78%2C84%2C100%2C102%2C128%2C131%2C137%2C147%2C152%2C167%2C169%2C189%2C191%2C214%2C222%2C250%2C264%2C323%2C324%2C326%2C346%2C354%2C357%2C362%2C370%2C377%2C401%2C403%2C444%2C453%2C460%2C469%2C24%2C77%2C142%2C151%2C218%2C251%2C372%2C398%2C406%2C455%2C367)%2C%22m2%22%22%23ffffb3%22(42%2C46%2C58%2C210%2C228%2C287%2C365%2C449%2C451%2C27%2C47%2C65%2C67%2C76%2C87%2C104%2C108%2C143%2C156%2C194%2C211%2C234%2C253%2C266%2C282%2C322%2C325%2C328%2C329%2C355%2C376%2C395%2C400%2C402%2C459%2C462%2C465%2C471%2C43%2C52%3A54%2C56%2C73%2C78%2C84%2C100%2C102%2C128%2C131%2C137%2C147%2C152%2C167%2C169%2C189%2C191%2C214%2C222%2C250%2C264%2C323%2C324%2C326%2C346%2C354%2C357%2C362%2C370%2C377%2C401%2C403%2C444%2C453%2C460%2C469%2C24%2C77%2C142%2C151%2C218%2C251%2C372%2C398%2C406%2C455%2C367)%2C%22m3%22%22%23bebada%22(42%2C46%2C58%2C210%2C228%2C287%2C365%2C449%2C451%2C27%2C47%2C65%2C67%2C76%2C87%2C104%2C108%2C143%2C156%2C194%2C211%2C234%2C253%2C266%2C282%2C322%2C325%2C328%2C329%2C355%2C376%2C395%2C400%2C402%2C459%2C462%2C465%2C471%2C43%2C52%3A54%2C56%2C73%2C78%2C84%2C100%2C102%2C128%2C131%2C137%2C147%2C152%2C167%2C169%2C189%2C191%2C214%2C222%2C250%2C264%2C323%2C324%2C326%2C346%2C354%2C357%2C362%2C370%2C377%2C401%2C403%2C444%2C453%2C460%2C469%2C24%2C77%2C142%2C151%2C218%2C251%2C372%2C398%2C406%2C455%2C367)%2C%22m4%22%22%23fb8072%22(42%2C46%2C58%2C210%2C228%2C287%2C365%2C449%2C451%2C27%2C47%2C65%2C67%2C76%2C87%2C104%2C108%2C143%2C156%2C194%2C211%2C234%2C253%2C266%2C282%2C322%2C325%2C328%2C329%2C355%2C376%2C395%2C400%2C402%2C459%2C462%2C465%2C471%2C43%2C52%3A54%2C56%2C73%2C78%2C84%2C100%2C102%2C128%2C131%2C137%2C147%2C152%2C167%2C169%2C189%2C191%2C214%2C222%2C250%2C264%2C323%2C324%2C326%2C346%2C354%2C357%2C362%2C370%2C377%2C401%2C403%2C444%2C453%2C460%2C469%2C24%2C77%2C142%2C151%2C218%2C251%2C372%2C398%2C406%2C455%2C367)%7D%2C&bins=21

### Observed behavior
* Error at phovea server:
```
api_1              | 09:51:44 INFO phovea_data_redis.assigner: create redis assigner
api_1              | [2017-07-20 09:52:07,270] ERROR in app: Exception on /matrix/tcgaKircMrna-Seq/hist [GET]
api_1              | Traceback (most recent call last):
api_1              |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1              |     response = self.full_dispatch_request()
api_1              |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1              |     rv = self.handle_user_exception(e)
api_1              |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1              |     reraise(exc_type, exc_value, tb)
api_1              |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1              |     rv = self.dispatch_request()
api_1              |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1              |     return self.view_functions[rule.endpoint](**req.view_args)
api_1              |   File "phovea_server/phovea_server/dataset_specific.py", line 322, in hist_matrix
api_1              |     hist, bin_edges = np.histogram(data, bins=int(ns.request.args.get('bins', np.sqrt(len(data)))), range=d.range)
api_1              |   File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 611, in histogram
api_1              |     n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
api_1              | ValueError: The first argument of bincount must be non-negative
```
* Can't add any other column in StratomeX afterwards.

### Problem:
Range of dataset (id=tcgaKircMrna-Seq) is wrong. There are elements with a value smaller than specified by range. 
Range from dataset: [-3.9958313880451723, 3.9958313880451723]
Actual lowest value:  -3.99583148956

**Comment by sgratzl** [comment]
could be a rounding error...
